---
# tasks file for workstation

- group:
    name: wheel
    state: present
    system: yes
  register: result      
         
- lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'    

- name: Configurando usuário "{{ create_user }}"
  user: 
    name: "{{ create_user }}"
    state: present  
    shell: /bin/bash 
    comment: "{{ comm_user }}"
    groups: wheel

- authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_key }}"
...
