---
# tasks file for workstation
- group:
    name: wheel
    state: present
    system: yes
  register: result      

- lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{lookup('file', 'templates/etc-sudoers.j2')}}"
    backup: yes
    validate: '/usr/sbin/visudo -cf %s'
           
- user: 
    name: "{{ create_user }}"
    state: present  
    shell: /bin/bash 
    comment: "{{ comm_user }}"
    groups: wheel

- authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_key }}"
...
