---
# tasks file for iac-ansible-workstation-environment

- group:
    name: wheel
    state: present
    system: yes
  register: result      
        
- name: Configurando usuário "lusar"
  user: 
    name: "{{ create_user }}"
    state: present  
    shell: /bin/bash 
    comment: "{{ comm_user }}"
    groups: wheel
...
