---
- hosts: workstation
  connection: local
  
  tasks:
 
  - package: 
      name: "{{ item }}" 
      state: latest
      update_cache: yes  
    loop:
      - chkrootkit
      - inotify-tools
      - rkhunter    
...
# apply sysctl config

# disable inative services

# install/config rkhunter

# install/config LMD

# install/config chkrootkit
