---
# tasks file for workstation

#- name: Configurar arquivo /etc/hosts
#  copy: src=etc-hosts 
#        dest=/etc/hosts 
#        owner=root 
#        group=root 
#        mode=0644
  
- name: Configurar arquivo /etc/hosts.allow 
  lineinfile: 
    path: /etc/hosts.allow
    line: "{{ item }}"
  with_items:
    - 'ALL: ALL: spawn /bin/echo "Tentativa de acesso em [$(/bin/date)] - Origem [ %u@%h (%n) ]" &>> /var/log/tcpwrappers.log'
  
- name: Configurar arquivo /etc/crontab
  lineinfile: 
    path: /etc/crontab
    line: "{{ item }}"
  with_items:
    - ' */30 *  *  *  * root /sbin/sysctl -w vm.drop_caches=3 2> /dev/null &> /dev/null'

- sysctl:
    name: "{{ item.name }}"
    state: present
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: 'kernel.nmi_watchdog',value: '0'}
    - { name: 'vm.drop_caches', value: '3'}
    - { name: 'vm.swappiness', value: '10}     

#- name: Configurar arquivo /etc/logrotate.d/personal
#  copy: src=etc-logrotate.d-personal dest=/etc/logrotate.d/personal owner=root group=root mode=0644
#
#- name: Configurar arquivo /etc/logrotate.d/ansible
#  copy: src=etc-logrotate.d-ansible dest=/etc/logrotate.d/ansible owner=root group=root mode=0644 
#
#- name: Configurar arquivo /etc/sudoers
#  copy: src=etc-sudoers dest=/etc/sudoers owner=root group=root mode=0440 

#    - name: Disable password authentication for root
#      lineinfile:
#        path: /etc/ssh/sshd_config
#        state: present
#        regexp: '^PermitRootLogin'
#        line: 'PermitRootLogin prohibit-password'
...
