---
- hosts: workstation
  connection: local
  
  tasks:
  - dnf: 
      name: "{{ item }}" 
      state: latest 
    loop:
      - bash-completion
      - bind-utils
      - bzip2
      - ccze
      - chrony
      - cifs-utils
      - curl
      - device-mapper-persistent-data 
      - dkms
      - dnf-automatic
      - dnf-plugins-core
      - dnf-utils
      - dropbox
      - easytag
      - ethtool
      - fedy	
      - gcc
      - gedit
      - git
      - git-core
      - gnome-gmail
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-common
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-drive-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-tweak-tool
      - google-chrome-stable
      - gstreamer
      - gstreamer-ffmpeg
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free
      - gstreamer-plugins-base
      - gstreamer-plugins-good
      - gstreamer-plugins-ugly
      - gstreamer1
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - htop
      - icedtea-web
      - java
      - java-openjdk
      - kernel-devel
      - kernel-headers
      - kernel-modules
      - kernel-tools
      - kernel-tools-libs
      - libcurl
      - libgudev
      - libreoffice-langpack-pt-BR
      - linux-firmware
      - lsof
      - lvm2
      - make
      - mlocate
      - mtr
      - nautilus-dropbox
      - net-tools
      - nfs-utils
      - nmap
      - ntfs-3g
      - numix-gtk-theme 
      - numix-icon-theme
      - numix-icon-theme-circle 
      - pinta
      - platform-python-dnf
      - python3-pip
      - remmina
      - remmina-plugins-rdp
      - rsync
      - screen
      - screenfetch
      - soundconverter
      - tcpdump
      - terminator
      - transmission
      - tree
      - tzdata
      - unzip
      - vim
      - vim-enhanced
      - vlc
      - wget
      - zip
 
### FingerPrint on DELL Latitude 3480 
#yum list fprintd libfprint
#fprintd-enroll myself
#systemctl status fprintd
#https://launchpad.net/~fingerprint/+archive/ubuntu/fingerprint-
#gdm-plugin-fingerprint
#http://en.community.dell.com/techcenter/os-applications/f/4613/t/20006668     
