---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: localhost
  connection: local
  
  vars_prompt:
    - name: "user"
      prompt: "Digite o nome do user"
      private: no

  tasks:
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: ansible_distribution == "Fedora"

- import_playbook: fedora-environment.yml
  tags: CONFIG   
    
- import_playbook: fedora-repo.yml
  tags: REPO

- import_playbook: fedora-package.yml
  tags: PACKAGE
  
- import_playbook: fedora-systemd.yml
  tags: SERVICE

- import_playbook: fedora-virtualbox.yml
  tags: VBOX 
  
- import_playbook: fedora-docker.yml
  tags: DOCKER  

- import_playbook: fedora-vagrant.yml
  tags: VAGRANT
...
