---
- hosts: all
  become: yes
  gather_facts: False

  tasks:

  - lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerSignature'
      state: absent

  - lineinfile:
      path: /etc/httpd/conf/httpd.conf
      state: present
      line: "ServerSignature Off"
