---
- hosts: all
  become: yes
  gather_facts: False

  tasks:

  - lineinfile:
      path: /etc/mail/sendmail.cf
      regexp: '^{{ item }}'
      state: absent
    loop:
      - O SmtpGreetingMessage=
    register: result
  
  - lineinfile:
      path: /etc/mail/sendmail.cf
      state: present
      line: "O SmtpGreetingMessage="

  - lineinfile:
      path: /etc/mail/sendmail.cf
      state: present
      line: "O DontBlameSendmail=safe"


  - file:
      path: /etc/mail/empty.txt
      state: touch
      owner: root
      group: root
      mode: 0640
    tags: file
    register: fileok

  # - replace:
  #     path: /etc/mail/sendmail.cf
  #     regexp: '^O HelpFile='
  #     replace: ''

  - lineinfile:
      path: /etc/mail/sendmail.cf
      state: present
      line: "O HelpFile=/etc/mail/empty.txt"

  # - replace:
  #     path: /etc/mail/sendmail.cf
  #     regexp: '^O PrivacyOptions='
  #     replace: ''

  - lineinfile:
      path: /etc/mail/sendmail.cf
      state: present
      line: "O PrivacyOptions=authwarnings,novrfy,noexpn,restrictqrun,restrictmailq"
